spring.application.name=EmployeeApplication
#server.port=8086

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

spring.data.mongodb.database=employee
spring.data.mongodb.uri=mongodb+srv://umarfarookj06:<root>@stublab.stwcb.mongodb.net/?retryWrites=true&w=majority&appName=Stublab